/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: amurin (https://sketchfab.com/amurin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-isometric-room-56cf7d5811304608b5e6d724195c6ccd
Title: Low Poly Isometric Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Apartment = (props) => {
    const { nodes, materials } = useGLTF('/models/low_poly_isometric_room.glb')
    return (
        <group {...props} dispose={null}>
            <group name="Habitacion_0" position={[0.095, -0.373, 0.14]} scale={4.819}>
                <mesh
                    name="Object_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.pared}
                />
                <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.suelo}
                />
                <mesh
                    name="Object_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials.afuera}
                />
                <mesh
                    name="Object_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials.puerta}
                />
                <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.negro}
                />
            </group>
            <group name="Cama_4" position={[-1.049, -0.692, 1.149]} scale={1.419}>
                <mesh
                    name="Object_16"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials.base_cama}
                />
                <mesh
                    name="Object_17"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials.colchon}
                />
            </group>
            <group name="Botella_17" position={[-3.882, 1.509, -2.596]} scale={0.12}>
                <mesh
                    name="Object_25"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials['Material.001']}
                />
                <mesh
                    name="Object_26"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials['Material.002']}
                />
            </group>
            <group name="Ordenador_19" position={[-3.958, 1.431, -3.489]} scale={0.077}>
                <mesh
                    name="Object_30"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials.negro}
                />
                <mesh
                    name="Object_31"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.pcinsidenormal}
                />
            </group>
            <group name="Pantalla_20" position={[-3.781, 2.47, -1.132]} scale={1.456}>
                <mesh
                    name="Object_33"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials.negro}
                />
                <mesh
                    name="Object_34"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_34.geometry}
                    material={materials.screen}
                />
            </group>
            <group name="Raton_21" position={[-2.793, 1.422, -2.237]} scale={[0.137, 0.04, 0.083]}>
                <mesh
                    name="Object_36"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials.negro}
                />
                <mesh
                    name="Object_37"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials.light}
                />
            </group>
            <group name="Teclado_23" position={[-2.859, 1.4, -1.158]} scale={[0.266, 0.019, 0.797]}>
                <mesh
                    name="Object_41"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_41.geometry}
                    material={materials.negro}
                />
                <mesh
                    name="Object_42"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={materials.material}
                />
            </group>
            <group
                name="Mesa_noche_25"
                position={[0.261, 0.659, -2.511]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-0.296, 0.034, 0.034]}>
                <mesh
                    name="Object_46"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_46.geometry}
                    material={materials.base_cama}
                />
                <mesh
                    name="Object_47"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_47.geometry}
                    material={materials.gris}
                />
            </group>
            <group name="Lampara_26" position={[0.245, 1.026, -3.312]} scale={[0.316, 0.045, 0.316]}>
                <mesh
                    name="Object_49"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_49.geometry}
                    material={materials.lamapra}
                />
                <mesh
                    name="Object_50"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_50.geometry}
                    material={materials.negro}
                />
            </group>
            <group
                name="Libros_28"
                position={[-2.771, 4.559, -3.744]}
                rotation={[Math.PI, 0, 2.849]}
                scale={[0.085, 0.433, 0.303]}>
                <mesh
                    name="Object_54"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_54.geometry}
                    material={materials.pages}
                />
                <mesh
                    name="Object_55"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_55.geometry}
                    material={materials.libro}
                />
            </group>
            <mesh
                name="Object_10"
                castShadow
                receiveShadow
                geometry={nodes.Object_10.geometry}
                material={materials.material_0}
                position={[-3.66, 0.011, 1.339]}
                scale={0.577}
            />
            <mesh
                name="Object_12"
                castShadow
                receiveShadow
                geometry={nodes.Object_12.geometry}
                material={materials.material_0}
                position={[-3.492, 0.078, 1.435]}
                rotation={[0, 0, -0.878]}
                scale={0.577}
            />
            <mesh
                name="Object_14"
                castShadow
                receiveShadow
                geometry={nodes.Object_14.geometry}
                material={materials.negro}
                position={[-3.58, 0.515, 1.407]}
                scale={0.394}
            />
            <mesh
                name="Object_19"
                castShadow
                receiveShadow
                geometry={nodes.Object_19.geometry}
                material={materials.sabanas}
                position={[3.11, 0.988, -3.333]}
                rotation={[0.604, 0, 0]}
                scale={[1.205, 1.596, 1.205]}
            />
            <mesh
                name="Object_21"
                castShadow
                receiveShadow
                geometry={nodes.Object_21.geometry}
                material={materials.sabanas}
                position={[3.211, 1.29, -0.072]}
                scale={[2.502, 1.205, 3.534]}
            />
            <mesh
                name="Object_23"
                castShadow
                receiveShadow
                geometry={nodes.Object_23.geometry}
                material={materials.negro}
                position={[-2.845, 1.371, -1.386]}
                scale={1.205}
            />
            <mesh
                name="Object_28"
                castShadow
                receiveShadow
                geometry={nodes.Object_28.geometry}
                material={materials.base_cama}
                position={[-2.943, 1.349, -2.506]}
                scale={[1.205, 0.12, 1.205]}
            />
            <mesh
                name="Object_39"
                castShadow
                receiveShadow
                geometry={nodes.Object_39.geometry}
                material={materials.silla2}
                position={[-2.496, -0.292, -0.907]}
                rotation={[-0.498, -1.215, 1.1]}
                scale={0.083}
            />
            <mesh
                name="Object_44"
                castShadow
                receiveShadow
                geometry={nodes.Object_44.geometry}
                material={materials.gris}
                position={[-4.157, 2.42, 4.442]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.111}
            />
            <mesh
                name="Object_52"
                castShadow
                receiveShadow
                geometry={nodes.Object_52.geometry}
                material={materials.base_cama}
                position={[-2.92, 4.041, -3.764]}
                scale={[1.205, 0.086, 0.455]}
            />
        </group>
    )
}

useGLTF.preload('/models/low_poly_isometric_room.glb')

export default Apartment;