/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import {useGLTF, useTexture} from '@react-three/drei'

const Desktop_blend = (props) => {
    const { nodes, materials } = useGLTF('/models/computer5.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={nodes.Plane.material}
                position={[0.503, -0.054, -0.58]}
            />
            <group
                position={[0.067, 0.465, -0.676]}
                rotation={[0, -0.032, 0]}
                scale={[0.171, 0.351, 0.429]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039.geometry}
                    material={materials.black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_1.geometry}
                    material={materials['Material.025']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_2.geometry}
                    material={materials['Material.024']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_3.geometry}
                    material={materials['red color']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_4.geometry}
                    material={materials['Material.022']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_5.geometry}
                    material={materials['Material.021']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_6.geometry}
                    material={materials['Material.020']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube039_7.geometry}
                    material={materials['Material.017']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.CABOARD.geometry}
                material={materials.wood}
                position={[-0.216, 0.438, -0.323]}
                rotation={[0, -0.032, 0]}
                scale={[0.862, 1.093, 0.514]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.KEYBOARD.geometry}
                material={materials.black}
                position={[0.459, 1.084, -0.295]}
                rotation={[0.029, -0.032, 0.001]}
                scale={[0.422, 0.005, 0.105]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.KEYBOARD001.geometry}
                    material={materials.black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane036.geometry}
                    material={nodes.Plane036.material}
                    position={[0.239, 1.878, 0.543]}
                    rotation={[1.15, -1.287, 1.427]}
                    scale={[0.003, 0.674, 0.005]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane037.geometry}
                    material={nodes.Plane037.material}
                    position={[0.111, 1.878, 0.543]}
                    rotation={[-1.992, 1.287, 1.715]}
                    scale={[0.003, 0.674, 0.005]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane038.geometry}
                    material={nodes.Plane038.material}
                    position={[0.174, 1.878, 0.543]}
                    rotation={[2.865, 0, -Math.PI]}
                    scale={[0.001, 0.674, 0.022]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane039.geometry}
                    material={nodes.Plane039.material}
                    position={[0.174, 1.735, 0.317]}
                    rotation={[-0.277, 0, 0]}
                    scale={[0.001, 0.674, 0.022]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text002.geometry}
                    material={nodes.Text002.material}
                    position={[-0.724, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text003.geometry}
                    material={nodes.Text003.material}
                    position={[-0.664, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text004.geometry}
                    material={nodes.Text004.material}
                    position={[-0.603, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text005.geometry}
                    material={nodes.Text005.material}
                    position={[-0.492, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text006.geometry}
                    material={nodes.Text006.material}
                    position={[-0.431, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text007.geometry}
                    material={nodes.Text007.material}
                    position={[-0.37, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text008.geometry}
                    material={nodes.Text008.material}
                    position={[-0.31, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text009.geometry}
                    material={nodes.Text009.material}
                    position={[-0.198, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text010.geometry}
                    material={nodes.Text010.material}
                    position={[-0.139, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text011.geometry}
                    material={nodes.Text011.material}
                    position={[-0.078, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text012.geometry}
                    material={nodes.Text012.material}
                    position={[-0.018, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text013.geometry}
                    material={nodes.Text013.material}
                    position={[0.109, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text014.geometry}
                    material={nodes.Text014.material}
                    position={[0.169, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text015.geometry}
                    material={nodes.Text015.material}
                    position={[0.23, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text016.geometry}
                    material={nodes.Text016.material}
                    position={[-0.903, 1.716, -0.465]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text018.geometry}
                    material={nodes.Text018.material}
                    position={[-0.832, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text019.geometry}
                    material={nodes.Text019.material}
                    position={[-0.769, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text020.geometry}
                    material={nodes.Text020.material}
                    position={[-0.705, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text021.geometry}
                    material={nodes.Text021.material}
                    position={[-0.641, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text022.geometry}
                    material={nodes.Text022.material}
                    position={[-0.577, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text023.geometry}
                    material={nodes.Text023.material}
                    position={[-0.513, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text024.geometry}
                    material={nodes.Text024.material}
                    position={[-0.449, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text025.geometry}
                    material={nodes.Text025.material}
                    position={[-0.389, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text026.geometry}
                    material={nodes.Text026.material}
                    position={[-0.325, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text027.geometry}
                    material={nodes.Text027.material}
                    position={[-0.26, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text028.geometry}
                    material={nodes.Text028.material}
                    position={[-0.196, 1.749, -0.413]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text029.geometry}
                    material={nodes.Text029.material}
                    position={[-0.141, 1.729, -0.443]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text031.geometry}
                    material={nodes.Text031.material}
                    position={[-0.128, 1.756, -0.401]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text032.geometry}
                    material={nodes.Text032.material}
                    position={[-0.041, 1.748, -0.414]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text033.geometry}
                    material={nodes.Text033.material}
                    position={[-0.885, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text034.geometry}
                    material={nodes.Text034.material}
                    position={[-0.799, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text035.geometry}
                    material={nodes.Text035.material}
                    position={[-0.736, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text036.geometry}
                    material={nodes.Text036.material}
                    position={[-0.672, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text037.geometry}
                    material={nodes.Text037.material}
                    position={[-0.609, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text038.geometry}
                    material={nodes.Text038.material}
                    position={[-0.545, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text039.geometry}
                    material={nodes.Text039.material}
                    position={[-0.482, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text040.geometry}
                    material={nodes.Text040.material}
                    position={[-0.418, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text041.geometry}
                    material={nodes.Text041.material}
                    position={[-0.355, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text042.geometry}
                    material={nodes.Text042.material}
                    position={[-0.291, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text043.geometry}
                    material={nodes.Text043.material}
                    position={[-0.228, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text044.geometry}
                    material={nodes.Text044.material}
                    position={[-0.164, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text045.geometry}
                    material={nodes.Text045.material}
                    position={[-0.101, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text046.geometry}
                    material={nodes.Text046.material}
                    position={[-0.047, 1.877, -0.21]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text047.geometry}
                    material={nodes.Text047.material}
                    position={[-0.783, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text048.geometry}
                    material={nodes.Text048.material}
                    position={[-0.72, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text049.geometry}
                    material={nodes.Text049.material}
                    position={[-0.656, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text050.geometry}
                    material={nodes.Text050.material}
                    position={[-0.593, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text051.geometry}
                    material={nodes.Text051.material}
                    position={[-0.529, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text052.geometry}
                    material={nodes.Text052.material}
                    position={[-0.466, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text053.geometry}
                    material={nodes.Text053.material}
                    position={[-0.403, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text054.geometry}
                    material={nodes.Text054.material}
                    position={[-0.339, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text055.geometry}
                    material={nodes.Text055.material}
                    position={[-0.276, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text056.geometry}
                    material={nodes.Text056.material}
                    position={[-0.212, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text057.geometry}
                    material={nodes.Text057.material}
                    position={[-0.148, 1.702, 0.08]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text058.geometry}
                    material={nodes.Text058.material}
                    position={[-0.02, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text059.geometry}
                    material={nodes.Text059.material}
                    position={[-0.749, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text060.geometry}
                    material={nodes.Text060.material}
                    position={[-0.686, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text061.geometry}
                    material={nodes.Text061.material}
                    position={[-0.622, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text062.geometry}
                    material={nodes.Text062.material}
                    position={[-0.559, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text063.geometry}
                    material={nodes.Text063.material}
                    position={[-0.495, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text064.geometry}
                    material={nodes.Text064.material}
                    position={[-0.432, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text065.geometry}
                    material={nodes.Text065.material}
                    position={[-0.368, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text066.geometry}
                    material={nodes.Text066.material}
                    position={[-0.305, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text067.geometry}
                    material={nodes.Text067.material}
                    position={[-0.241, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text068.geometry}
                    material={nodes.Text068.material}
                    position={[-0.186, 1.827, 0.277]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text069.geometry}
                    material={nodes.Text069.material}
                    position={[-0.02, 1.845, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text070.geometry}
                    material={nodes.Text070.material}
                    position={[-0.885, 1.895, -0.182]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text071.geometry}
                    material={nodes.Text071.material}
                    position={[-0.87, 1.688, 0.057]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text072.geometry}
                    material={nodes.Text072.material}
                    position={[-0.174, 1.869, -0.223]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text073.geometry}
                    material={nodes.Text073.material}
                    position={[-0.11, 1.862, -0.234]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text074.geometry}
                    material={nodes.Text074.material}
                    position={[-0.031, 1.904, -0.167]}
                    rotation={[0.047, 0.467, -0.28]}
                    scale={[0.029, 1.305, 0.056]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text076.geometry}
                    material={nodes.Text076.material}
                    position={[-0.161, 1.678, 0.042]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text077.geometry}
                    material={nodes.Text077.material}
                    position={[-0.87, 1.844, 0.305]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text078.geometry}
                    material={nodes.Text078.material}
                    position={[-0.317, 1.818, 0.263]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text079.geometry}
                    material={nodes.Text079.material}
                    position={[-0.251, 1.816, 0.259]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text080.geometry}
                    material={nodes.Text080.material}
                    position={[-0.173, 1.851, 0.316]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text081.geometry}
                    material={nodes.Text081.material}
                    position={[-0.885, 1.709, 0.56]}
                    rotation={[0.074, 0, 0]}
                    scale={[0.015, 1.305, 0.061]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text082.geometry}
                    material={nodes.Text082.material}
                    position={[-0.817, 1.709, 0.56]}
                    rotation={[0.074, 0, 0]}
                    scale={[0.015, 1.305, 0.061]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text083.geometry}
                    material={nodes.Text083.material}
                    position={[-0.691, 1.709, 0.56]}
                    rotation={[0.074, 0, 0]}
                    scale={[0.015, 1.305, 0.061]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text084.geometry}
                    material={nodes.Text084.material}
                    position={[-0.2, 1.709, 0.56]}
                    rotation={[0.074, 0, 0]}
                    scale={[0.015, 1.305, 0.061]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text085.geometry}
                    material={nodes.Text085.material}
                    position={[-0.136, 1.709, 0.56]}
                    rotation={[0.074, 0, 0]}
                    scale={[0.015, 1.305, 0.061]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text086.geometry}
                    material={nodes.Text086.material}
                    position={[-0.006, 1.709, 0.56]}
                    rotation={[0.074, 0, 0]}
                    scale={[0.015, 1.305, 0.061]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text087.geometry}
                    material={nodes.Text087.material}
                    position={[0.11, 1.722, -0.456]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text088.geometry}
                    material={nodes.Text088.material}
                    position={[0.173, 1.722, -0.456]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text089.geometry}
                    material={nodes.Text089.material}
                    position={[0.238, 1.721, -0.456]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text090.geometry}
                    material={nodes.Text090.material}
                    position={[0.11, 1.796, -0.183]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text091.geometry}
                    material={nodes.Text091.material}
                    position={[0.174, 1.796, -0.183]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text092.geometry}
                    material={nodes.Text092.material}
                    position={[0.238, 1.796, -0.183]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text093.geometry}
                    material={nodes.Text093.material}
                    position={[0.331, 1.719, -0.46]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text094.geometry}
                    material={nodes.Text094.material}
                    position={[0.394, 1.75, -0.411]}
                    rotation={[0.011, -0.378, 0.223]}
                    scale={[0.044, 2.594, 0.117]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text095.geometry}
                    material={nodes.Text095.material}
                    position={[0.457, 1.761, -0.393]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.029, 2.527, 0.117]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text096.geometry}
                    material={nodes.Text096.material}
                    position={[0.522, 1.749, -0.412]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.048, 4.192, 0.194]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text097.geometry}
                    material={nodes.Text097.material}
                    position={[0.334, 1.92, -0.142]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.192, 0.101]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text098.geometry}
                    material={nodes.Text098.material}
                    position={[0.331, 2.076, 0.105]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text101.geometry}
                    material={nodes.Text101.material}
                    position={[0.459, 1.914, -0.152]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text108.geometry}
                    material={nodes.Text108.material}
                    position={[0.397, 2.079, 0.11]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text109.geometry}
                    material={nodes.Text109.material}
                    position={[0.396, 1.922, -0.139]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text110.geometry}
                    material={nodes.Text110.material}
                    position={[0.458, 2.079, 0.11]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text111.geometry}
                    material={nodes.Text111.material}
                    position={[0.331, 2.223, 0.338]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text112.geometry}
                    material={nodes.Text112.material}
                    position={[0.397, 2.226, 0.342]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text113.geometry}
                    material={nodes.Text113.material}
                    position={[0.458, 2.226, 0.342]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text114.geometry}
                    material={nodes.Text114.material}
                    position={[0.33, 2.402, 0.621]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text115.geometry}
                    material={nodes.Text115.material}
                    position={[0.457, 2.402, 0.621]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text116.geometry}
                    material={nodes.Text116.material}
                    position={[0.522, 1.952, -0.092]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.025, 2.156, 0.1]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text117.geometry}
                    material={nodes.Text117.material}
                    position={[0.523, 2.308, 0.472]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.012, 1.024, 0.047]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text118.geometry}
                    material={nodes.Text118.material}
                    position={[-0.784, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text119.geometry}
                    material={nodes.Text119.material}
                    position={[-0.897, 1.519, -0.776]}
                    rotation={[-0.037, 0, 0]}
                    scale={[0.015, 1.305, 0.06]}
                />
            </mesh>
            <group
                position={[0.494, 1.409, -0.613]}
                rotation={[0, -0.032, 0]}
                scale={[0.486, 0.231, 0.009]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube036.geometry}
                    material={materials.black}
                >
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube036_1.geometry}
                    material={materials['Material.022']}
                >
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube036_2.geometry}
                    material={materials['Material.021']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MOUSE.geometry}
                material={materials.black}
                position={[0.898, 1.087, -0.28]}
                rotation={[0, 1.538, 0]}
                scale={0.019}
            />
            <group position={[-0.198, 1.132, -0.615]} rotation={[0, -0.063, 0]} scale={0.049}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube033.geometry}
                    material={materials.black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube033_1.geometry}
                    material={materials['Material.022']}
                />
            </group>
            <group position={[1.167, 1.132, -0.637]} rotation={[0, -0.063, 0]} scale={0.049}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube034.geometry}
                    material={materials.black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube034_1.geometry}
                    material={materials['Material.022']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.WHEEL.geometry}
                material={materials.black}
                position={[1.184, 0.056, -0.114]}
                rotation={[Math.PI / 2, 0, -1.538]}
                scale={0.035}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.WHEEL_1.geometry}
                material={materials.black}
                position={[1.214, 0.056, -1.039]}
                rotation={[Math.PI / 2, 0, 1.603]}
                scale={0.035}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.WHEEL_2.geometry}
                material={materials.black}
                position={[-0.24, 0.057, -0.152]}
                rotation={[-Math.PI / 2, 0, -1.603]}
                scale={[-0.035, -0.028, -0.035]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.WHEEL_3.geometry}
                material={materials.black}
                position={[-0.21, 0.057, -1.077]}
                rotation={[-Math.PI / 2, 0, 1.538]}
                scale={-0.035}
            />
        </group>
    )
}

useGLTF.preload('/models/computer5.glb')
export default Desktop_blend;